### ISSUE TITLE
Dynamic Keys

### ISSUE THREAD

**Issue by Duskanroc57** [JsonAsAsset/JsonAsAsset#50]
The installation guide never mentions the dynamic keys, but the images show that they're there, but not what they are. I assume they're different for every game or something like that, but the guide doesn't say anything about them so I don't know how to get them, and I never needed them for FModel.

**Comment by Tectors** [comment]
If you don't use AES Keys in FModel and everything works fine, then it's not needed in JsonAsAsset.
