### ISSUE TITLE
Cant get custom fmodel build cuz discord link not working

### ISSUE THREAD

**Issue by DeadlyParkourKillerDarkAssasinStalker** [JsonAsAsset/JsonAsAsset#51]

**Comment by Tectors** [comment]
What's your discord username and are you in the discord.

**Comment by DeadlyParkourKillerDarkAssasinStalker** [comment]
My username is notimportant2004, yes i am

**Comment by Tectors** [comment]
![image](https://github.com/user-attachments/assets/3080a783-a425-46a2-989d-dca5b83ab183)

**Comment by DeadlyParkourKillerDarkAssasinStalker** [comment]
Sorry for the confusion, I didn't know you meant a discord server. I'm not in any server right now, my problem is that I can't access the jsonasasset discord server at all because I get this error when I try join.
![2024-12-20](https://github.com/user-attachments/assets/0af9c00c-867f-44a9-b3c6-3f624116995e)

**Comment by Tectors** [comment]
https://discord.gg/RmEJuTar

**Comment by DeadlyParkourKillerDarkAssasinStalker** [comment]
it worked thanks

**Comment by brocococonut** [comment]
@Tectors Could I please also get an invite link?

**Comment by Tectors** [comment]
It's in the GitHub's readme

**Comment by brocococonut** [comment]
It says it's invalid 😓

**Comment by Tectors** [comment]
Try now

**Comment by brocococonut** [comment]
Thank youuu
And thanks for being exceptionally fast ahaha
